---
- hosts: web_nodes
  become: yes
  vars:
   metrics_storage_ip: 172.31.19.63
   db_ip: 172.31.18.254
  tasks:
    - name: "Install apache server"
      yum:
        name: httpd
        state: latest
    - name: "Install php"
      yum:
        name: "{{packages}}"
        state: latest
      vars:
        packages:
          - php-mysql
          - php
    - name: "Download wp"
      get_url:
        url: https://wordpress.org/latest.zip
        dest: /tmp/wordpress.zip
    - name: "Unarchive wp to destination"
      unarchive: 
        src: /tmp/wordpress.zip
        dest: /var/www
        remote_src: yes
    - name: "Put apache config to the right place"
      copy: 
        src: ./templates/blog.conf
        dest: /etc/httpd/conf.d/blog.conf
    - name: "Start service httpd, if not started"
      service:
        name: httpd
        state: restarted
    - name: "Copy wp-config"
      template:
        src: ./templates/wp-config.php
        dest: /var/www/wordpress/wp-config.php
    - name: "install telegraph"
      yum:
       name: https://dl.influxdata.com/telegraf/releases/telegraf-1.8.3-1.x86_64.rpm
       state: present
    - template:
       src: templates/telegraf.conf
       dest: /etc/telegraf/telegraf.conf
    - service:
       name: telegraf
       state: restarted

- hosts: db_nodes
  become: yes
  tasks:
   - name: "Install my-sqls"
     yum:
      name: "{{packages}}"
      state: present
     vars:
      packages:
      - mariadb
      - mariadb-server
      - MySQL-python
   - name: "Start service mariadb, if not started"
     service:
       name: mariadb
       state: started
   - name: "Create database named wp_database"
     mysql_db:
       name: wp_database
       state: present
   - mysql_user:
       name: root
       password:
       priv: '*.*:ALL'
       host: '%'
       state: present
- hosts: stats_nodes
  become: yes
  tasks:
   - name: "install grafana"
     yum: 
      name: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.3.4-1.x86_64.rpm
      state: present
   - service:
      name: grafana-server
      state: restarted   